name: walkmeter
description: "Test app for interview on rabota.by"
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  equatable:
  bloc:
  pedometer_2: ^5.0.3
  flutter_background_service:
  shared_preferences: ^2.2.3
  duration: ^3.0.13
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
